### PR TITLE
Tribe mentions

### PR DESCRIPTION
**Pull request by toadlyBroodle**
main branch: 
-add catch for common crash I was having regarding improper casting

tribe_mentions branch:
-add popup picker of tribe member aliases when '@' entered according to [issue 510](https://github.com/stakwork/sphinx-kotlin/issues/510) specifications

### CODE REVIEW

**Comment by tomastiminskas** [comment]
Hey. I was checking and testing and here are some changes/corrections we need to do:
- Let's make the ListView to show over the chat view. Right now it's moving the chat view to the top, but that's not needed since the suggestions list view will show just when typing mentions and it will disappear. So the list view should show over the chat list, just above the text field as it's showing.
- The list of suggestions shouldn't show until you type a first letter after the @. It shouldn't show when typing @ and showing all members, since there could be lots of members on a tribe
- This way of getting a reference of a UI element is not right:

`tribeMembersMentionListView = activity?.findViewById(R.id.listview_mention_tribe_members) as ListView`

You should do this instead to be consistent with how it's done all over the app

`binding.listviewMentionTribeMembers`

- Let's create a custom layout for each suggestion item and make it more consistent with iOS design.
- The array of messages I mentioned is `messageHolderViewStateFlow`, which is actually a `MutableStateFlow` containing a `List<MessageHolderViewState>`. Each MessageHolderViewState contains the message, so you could iterate the `messageHolderViewStateFlow.value` and check there instead of creating a new array as you are doing. 
- Finally all the logic shouldn't be on the ChatTribeFragment as you did it. There is a way all the app is done. The logic goes in the viewModels, and the views (fragments) just listen to ViewState changes and show them. So on the `onTextChanged` of the ChatFragment, you need to call a function on the `ChatTribeViewModel` where the logic will be. Then you will need to create a `MutableStateFlow` like the `messageHolderViewStateFlow` containing a List<String> that will set on the viewModel every time a character is typed after the @. The view will collect the view state on the `subscribeToViewStateFlow()` as it collects any other viewState and will build the list there. The `setOnItemClickListener` of the mentionsListView can stay the same but out of the `footerBinding.editTextChatFooter.addTextChangedListener`

**Comment by toadlyBroodle** [comment]
Ok understood. Thanks for the specific feedback. I'll let you know when these changes are done.

**Comment by toadlyBroodle** [comment]
Here's an overview of the above changes according to your above requests:
-get resource references from bindings instead of findViewById()
-create custom formatted ListView for mention suggestions popup
-make mention popup overlay chat view instead of displacing it
-syle mention popup in accordance with app theme
-don't show mention popup until first character after @ is typed
-move logic from ChatTribeFragment to ChatTribeViewModel

-also fixed a bug where previously entered aliases were getting deleted upon additional similar/same aliases added

I'm sorry, I can't seem to figure out how the HolderViewStateFlow, MutableStateFlow system works and I can't figure out how to access the private/suspended messageHolderViewStateFlow.value from viewModel or fragment. Can you please provide specific examples?

Demo 3:

**Comment by tomastiminskas** [comment]
It won't be easy to provide more details. But I can do the remaining changes so then you can review them. And we could do a call so I can explain you more in details once they are done. That would help in case you won't to take another task in this project.

**Comment by toadlyBroodle** [comment]
Sure that sounds great, I'll definitely be working with you on Sphinx into the future and eager to learn as much about the codebase as possible. Thanks!

**Comment by toadlyBroodle** [comment]
Awesome thanks, always interested in learning to become better dev.

**Comment by toadlyBroodle** [comment]
Awesome thanks, fetched your branch and had a look at how you're organizing things in Sphinx. Tested your changes, looks good with no issues found. Your changes help me understand more about how StateFlow/ShareFlow work. Look forward to working more with you in the future :)

**Pull request closed without merging**
