### PR TITLE
Kg/feature/play audio attachment

### PR DESCRIPTION
**Pull request by kngako**
https://github.com/stakwork/sphinx-kotlin/issues/303

### CODE REVIEW

**Review by 05nelsonm — CHANGES_REQUESTED** [review]
- Current implementation does not listen for and pass device audio focus when other media is played, or call is made/received.
- Current implementation does not handle dragging of the audio bar to a different time.
- Navigating to a detail screen from the chat while audio is playing should pause the audio playback.

**Comment by 05nelsonm** [comment]
Overall, the architecture of this implementation needs to be re-thought.

The appropriate layer in the view's hierarchy to cache playback metadata for the message would be the `ViewModel`, as they will navigate back to the chat screen whereby the view needs to be set the the appropriate time where they left off.

I would suggest a separate `ViewModel` known only by the `chat-common` module to handle all media playback, and to keep things separated from the `ChatViewModel`.

This will allow for the caching of playback state for messages that are played (ex: `MutableMap<MessageId, AudioPlaybackStateData>`) such that upon setting of the view, if `isAudioAttachment` is true, can retrieve the stateful playback data (if it exists) from the cache and appropriately set the view.

It will also enable more cleanly handling of device audio focus.

As much as I'd like to use the `MediaPlayerService`, I do not think it is appropriate to do so as the underlying data is specific to that message (and thus chat), so playback should be handled within the screen module instead of a service.

**Comment by tomastiminskas** [comment]
@kngako this item "Current implementation does not handle dragging of the audio bar to a different time" can be excluded of the first version since that is not implemented on iOS neither. We can do it later as a separated task

**Review by 05nelsonm — APPROVED** [review]
Approving for now to get feature in to Friday's release, but there are severe architectural issues and anti-patterns which remain unaddressed from the requested changes.

A refactor for this feature is being done on branch `mn/fix/play-audio-attachment`. Would strongly suggest looking at it when the PR is ready.

**Comment by 05nelsonm** [comment]
Closing in favor of #319

**Pull request closed without merging**
